# -*- coding: utf-8 -*-
"""Question4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6tcZY5lDAmvP_bCXLpx_ZMG90q2NvIu
"""

from google.colab import files
s =files.upload()

df= pd.read_excel('Customer_Transaction.xlsx',header=0)

unique_stores = df['Store_Code'].unique()
unique_customers = df['Customer_ID'].unique()
len(unique_stores)



c = 0
visit = []

for customer in unique_customers:
    visit_counts = []
    
    for store in unique_stores:
        temp = df[(df['Store_Code'] == store) & (df['Customer_ID'] == customer)]
        visit_counts.append(temp.shape[0])
        
    total = sum(visit_counts)
    visit_counts[:] = [x / total for x in visit_counts]
    c = c+1
    visit.append(visit_counts)
    if c%100 ==0:
      print(c)

data = pd.DataFrame(visit)

#Using group 
Grouped_data = dataFile[['Store_Code','Customer_ID']].groupby(['Customer_ID'])
df = pd.read_csv(r"C:\Users\Aswath\Desktop\Buckman_Data\prob4.csv" , encoding="ISO-8859-1
for key, item in Grouped_data:
    Temp = Grouped_data.get_group(key)
    customer = Temp.iloc[0,1]
    count = Temp.shape[0]
    df.iloc[D_customer[customer],D_store[store]] = count

total = sum(visit_counts)
visit_counts[:] = [x / total for x in visit_counts]

data
data.to_csv('prob.csv', encoding='utf-8')

files.download('prob.csv')